[package]
name = "kenjutsu-nvim"
version = "0.2.4"
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Kenjutsu Neovim backend — daemon for the Neovim plugin"
edition = "2024"

[[bin]]
name = "kjn"
path = "src/main.rs"

[features]
vendored-openssl = ["git2/vendored-openssl"]

[dependencies]
anyhow = { workspace = true }
comment-commit = { workspace = true }
git2 = { workspace = true }
kenjutsu-core = { workspace = true }
kenjutsu-types = { workspace = true, features = ["serde"] }
marker-commit = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
